ICONS_WILDS = [
    "Pouch",
    "Question Mark",
    "Rare Question Mark",
    "Negative",
    "Cross",
    "Mushroom",
    "Egg",
    "Webbing",
    "Herb",
    "Medicine",
    "Sac",
    "Whetstone",
    "Pill",
    "Fish",
    "Meat",
    "Barrel",
    "Bomb",
    "Box",
    "Trap",
    "Ball",
    "Smoke Bomb",
    "Bait",
    "Boomerang",
    "Horn",
    "Binoculars",
    "Knife",
    "Spit",
    "Book",
    "Meal Ticket",
    "Ticket",
    "Coin",
    "Husk",
    "Ammo",
    "Empty Phial",
    "Coating",
    "Spiderweb",
    "Seed",
    "Ore",
    "Bug",
    "Dung",
    "Monster Part",
    "Bone",
    "Scale",
    "Hide",
    "Claw",
    "Shell",
    "Tail",
    "Wing",
    "Head",
    "Plate",
    "Pallium",
    "Crystal",
    "Scrap",
    "Relic",
    "Armor Sphere",
    "Decoration",
    "Decoration 1",
    "Decoration 2",
    "Decoration 3",
    "Decoration 4",
    "Tent",
    "Slinger",
    "Net",
    "SOS",
    "Music",
    "Seikret",
    "Ammo Spread",
    "Ammo Pierce",
    "Ammo Sticky",
    "Ammo Cluster",
    "Vial",
    "Drug",
    "Chemical",
    "Cape",
    "Ingredient Meat",
    "Ingredient Vegetable",
    "Ingredient Cheese",
    "Ingredient Mushroom",
    "Ingredient Shrimp",
    "Ingredient Garlic",
    "Ingredient Egg",
    "Lucky Voucher",
    "unk2",
    "unk3",
    "unk4",
    "Map",
    "Corpse",
    "None",
]

SKILL_ICONS_WILDS = [
    "Attack",
    "Affinity",
    "Element",
    "Whetstone",
    "Ammo",
    "Defense",
    "Health",
    "Stamina",
    "Power",
    "Calm",
    "Sac",
    "Pouch",
    "Armor Group",
    "Armor Series",
]

ADD_ICON_POS = {
        "RT": (100 - 32, 0),
        "LT": (0, 0),
        "RB": (100 - 32, 100 - 32),
        "LB": (0, 100 - 32),
        "CT": (100 - 32, 100 - 32),
}

FLAIR_MAP = { x: i for i, x in enumerate([
        "GREAT",
        "SHELL_LV1",
        "SHELL_LV2",
        "SHELL_LV3",
        "UNMAKABLE",
        "MAKABLE",
        "SUPPLY",
        "CLEAR_ITEM",
        "WISH_ITEM",
        "ATTR_FIRE",
        "ATTR_WATER",
        "ATTR_ICE",
        "ATTR_ELEC",
        "ATTR_DRAGON",
        "ATTR_POISON",
        "ATTR_PARALYSIS",
        "ATTR_SLEEP",
        "ATTR_BOMB",
        "NON_TARGET",
        "RECIPE",
        "POSSESS",
        "FITTING",
        "EQUIPPED",
        "FORGEABLE",
        "HIGHLIGHT_MAIN",
        "HIGHLIGHT_USER",
        "EX_RECOMMEND",
        "FIXEDITEM",
        "FIXEDITEM_OFF",
        "ROTTING_CORPSE",
        "INGREDIENTS",
        "LOCK",
        "POSSESS_MULTI",
        "CHECK",
        "REPLACE",
        "CRYSTAL_CORPSE",
        "UNIDENTIFIED",
        "FOR_ATTACK",
        "MAX"
])}
